name: Auto update

on:
  push:
    branches:
      - main

jobs:
  run-akashi-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - run: poetry install --no-interaction

      - name: Run akashi_schedule
        run: |
          poetry run python -m script.akashi_schedule

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "GitHub Actions Update"
          add: "data/*"
          new_branch: data_update_${{github.run_id}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create pull request
        run: gh pr create --title 'Data Update' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}